site_name: 瞬间Resources
site_author: "Komorebi"
site_url: "https://mk.tripper.press"
extra_css:
  - css/extra.css
# Repository
repo_name: "GitHub"
repo_name: aiokr/Tripper-Docs-Mkdocs
repo_url: "https://github.com/aiokr/Tripper-Docs-Mkdocs"
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
